version: 2
updates:
- package-ecosystem: "gradle"
  directory: "/"
  schedule:
    interval: "daily"
    time: "06:00"
    timezone: "Asia/Kolkata"
  reviewers:
     - "EphemeralG"
     - "dhavalgoti24"
