name: Release
on:
  push:
    tags:
      - 'r*'
jobs:
  build:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: set up signing configs
      run: chmod +x release/setup.sh && release/setup.sh "$KEY"
      env:
        KEY: ${{ secrets.KEY }}

    - name: Generate cache key
      run: chmod +x .github/checksum.sh && ./.github/checksum.sh checksum.txt

    - name: Cache gradle modules
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/modules-2
        key: ${{ runner.os }}-gradlemodules-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlemodules-

    - name: Cache gradle jars
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/jars-3
        key: ${{ runner.os }}-gradlejars-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlejars-

    - name: Cache gradle build
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches/build-cache-1
        key: ${{ runner.os }}-gradlebuildcache-${{ hashFiles('checksum.txt') }}
        restore-keys: |
          ${{ runner.os }}-gradlebuildcache-

    - name: Build release binaries
      run: chmod +x gradlew ; ./gradlew :app:assembleRelease

    - name: Upload OpenIndic arm64-v8a Release apk
      uses: actions/upload-artifact@v2
      with:
        name: OpenIndic arm64-v8a Release apk
        path: app/build/outputs/apk/release/OpenIndic-arm64-v8a-release.apk

    - name: Upload OpenIndic armeabi-v7a Release apk
      uses: actions/upload-artifact@v2
      with:
        name: OpenIndic armeabi-v7a Release apk
        path: app/build/outputs/apk/release/OpenIndic-armeabi-v7a-release.apk

    - name: clean up signing configs
      if: always()
      run: chmod +x release/cleanup.sh && release/cleanup.sh

  create_github_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Get OpenIndic arm64-v8a Release apk
        uses: actions/download-artifact@v2
        with:
          name: OpenIndic arm64-v8a Release apk
          path: artifacts

      - name: Get OpenIndic armeabi-v7a Release apk
        uses: actions/download-artifact@v2
        with:
          name: OpenIndic armeabi-v7a Release apk
          path: artifacts

      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v1.1.0
        with:
          version: ${{ github.ref }}
          path: ./CHANGELOG.md

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.log_entry }}
          draft: true
          prerelease: false

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Upload OpenIndic arm64-v8a Release apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/OpenIndic-arm64-v8a-release.apk
          asset_name: OpenIndic-${{ steps.get_version.outputs.VERSION }}_arm64-v8a.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload OpenIndic armeabi-v7a Release apk
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/OpenIndic-armeabi-v7a-release.apk
          asset_name: OpenIndic-${{ steps.get_version.outputs.VERSION }}_armeabi-v7a.apk
          asset_content_type: application/vnd.android.package-archive